accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views
app_name = 'articles'
urlpatterns = [
    path('', views.articlelist, name='list'),
    path('create/', views.article_create, name='create'),
    path('<slug>/', views.article_detail, name='detail'),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('', views.homepage),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls'))

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

    def snippit(self):
        return self.body[:50] + "...."

articles/forms.py
from django import forms
from . import models


class CreatArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:

                return redirect('articles:list')

    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.


def articlelist(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html',
                  {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url='/accounts/login')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreatArticle(request.POST, request.FILES)
        if form.is_valid():
            return redirect('articles:list')

    else:
        form = forms.CreatArticle()
    return render(request, 'articles/article_create.html', {'form': form})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    # return HttpResponse("Home page")
    return render(request, 'home.html')


def about(request):
    # return HttpResponse("About page")
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="/accounts/login/" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit"  value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Sign Up</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit"  value="SignUp">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="creat-article">
        <h1>Creat an Awesome article</h1>
        <form class="site-form" action="/articles/create/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit"  value="Create">

        </form>

    </div>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="details">
    <div class="detail">
        <img src="{{article.thumb.url}}" alt="">
        <h1>{{article.title}}</h1>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>

    </div>

</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Article_list</h1>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
                <p>{{article.snippit}}</p>
                <p>{{article.date}}</p>

            </div>
        {% endfor %}

    </div>

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>about</title>
    </head>
    <body>
        <h1> About Us </h1>
        <p>You are looking at about us page</p>
    </body>
</html>

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <h1><a href="{% url 'articles:list' %}"> <img src="{% static 'logo.png' %}" alt=""> </a></h1>
        <nav>
            <ul>
            <li>
                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Log Out</button>

                </form>
            </li>
        </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/home.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Home Page</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <h1><a href="{% url 'articles:list' %}"> <img src="{% static 'logo.png' %}" alt=""> </a></h1>

        <h1>Home</h1>
        <p>You are looking at home page</p>

        <ul>
            <li> <a href="{% url 'articles:list' %}">Articles</a> </li>
            <li> <a href="{% url 'accounts:signup' %}">Create account</a> </li>
            <li> <a href="{% url 'accounts:login' %}">Log in to your account</a> </li>
        </ul>

    </body>
</html>